### ISSUE TITLE
How to use 4 USB webcam with NVIDIA Jetson TX2 using USB hub?

### ISSUE THREAD

**Issue by ankitagr92** [saiprashanths/dl-docker#95]
Hello,
I am trying to use 4 USB webcams with NVIDIA jetson TX2 but I am unable to get the output, the program shows the following error:
VIDIOC_QUERYCTRL: Input/output error
VIDIOC_STREAMON: No space left on device
VIDIOC_STREAMON: No space left on device
Traceback (most recent call last):
File "multiCameraProcessing.py", line 73, in <module>
CaptureImages()
File "multiCameraProcessing.py", line 70, in __init__
self.processImages()
File "multiCameraProcessing.py", line 51, in processImages
frame3_undistort = self.undistort.image_undistort(frame3, camera_name_right)
File "/home/nvidia/Desktop/Thesis/Programs_v3/Undistortion.py", line 25, in image_undistort
dim1 = image.shape[:2][::-1]
AttributeError: 'NoneType' object has no attribute 'shape'

Please suggest a solution on how to use 4 USB webcams together

**Comment by ex00** [comment]
Hi @ankitagr92,
Do you try to use web cam inside dl-docker image? 
I think that the more suitable place for ask question about NVIDIA products is community forum: https://forums.geforce.com/default/board/25/nvidia-community/

**Comment by diffgg** [comment]
hi, @ankitagr92 , I have met exact the same problem. Did you fixed it?

**Comment by diffgg** [comment]
Hi, @ankitagr92 , I have met exact the same problem. Did you fix it?
